version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
        environment:
          DEPLOY_HOST: 139.162.179.147
    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "package.json" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#
      - run:
          command: npm install
          name: Installing Dependencies
#
#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running build script for master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              chmod u+x ./deployments/build_prod.sh
              npm run build-prod
              sudo apt install rsync
              ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
            fi

      - run:
          name: Running build script for develop branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              chmod u+x ./deployments/build_prod.sh
              npm run build-prod
              sudo apt install rsync
              ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
            fi

      - deploy:
          name: Deploy master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              chmod u+x ./deployments/deploy_prod.sh
              ./deployments/deploy_prod.sh
            fi

      - deploy:
          name: Deploy develop branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]
            then
              chmod u+x ./deployments/deploy_prod.sh
              ./deployments/deploy_prod.sh
            fi
